# -*- coding: utf-8 -*-
from __future__ import unicode_literals
names = [
    'Abassi', 'Abiku', 'Abuk', 'Achimi', 'Adriambahomanana', 'Adro', 'Adroa', 'Adroanzi', 'Age', 'Aha', 'Njoku', 'Aho',
    'Aigamuxa', 'Aje', 'Shaluga', 'Ajok', 'Akongo', 'Ala', 'Ale', 'Alla', 'Alouroua', 'Amma', 'Ananse', 'Anansi',
    'Andriamahilala', 'Andriambahomanani', 'Andumbulu', 'Ane', 'Anotchi', 'Asa', 'Atai', 'Ataokoloinona', 'Aunt',
    'Nancy', "Azra'il", 'Azrail', 'Ba', 'Dimo', 'Babalu', 'Aye', 'Babaluaye', 'Babayanmi', 'Badimo', 'Banga', 'Bayani',
    'Bayanni', 'Bomazi', 'Buk', 'Buku', 'Bumba', 'Cagn', 'Candit', 'Cghene', 'Chango', 'Chedi', 'Chiuta', 'Chonganda',
    'Chuku', 'Da', 'Dada', 'Deng', 'Ditaolane', 'Domfe', 'Dongo', 'Dubiaku', 'Dxui', 'Dyinyinga', 'Dziva', 'Ebore',
    'Eda', 'Edinkira', 'Egungun', 'Oya', 'Ekurana', 'Eleduwa', 'Elegua', 'Elusu', 'En', 'Kai', 'Enekpe', 'Engai',
    'Enkai', 'Eseasar', 'Eshu', 'Esu', 'Evus', 'Fa', 'Faro', 'Ga', 'Gorib', 'Gamab', 'Gaunab', 'Ghekre', 'Gu', 'Gunab',
    'Haitse', 'Aibeb', 'Haitsi', 'Haiuri', 'Hare', 'Heitsi', 'Eibib', 'Huntin', 'Huveane', 'Hyel', 'Taku', 'Iamanjie',
    'Ida', 'Imana', 'Itherther', 'Iyakare', 'Jakuta', 'Jok', 'Odudu', 'Juok', 'Kaang', 'Kabundungulu', 'Kaka', 'Guie',
    'Kalumba', 'Kammapa', 'Kanu', 'Katonda', 'Khakhabaisaywa', 'Khodumodurno', 'Khonvoum', 'Khuzwane', 'Kwoth', 'Le',
    'Eyo', 'Legba', 'Lela', 'Leza', 'Libanza', 'Maori', 'Massim', 'Biambe', 'Mawu', 'Lisa', 'Mbaba', 'Mwanna', 'Waresa',
    'Mbere', 'Mbokomu', 'Mbombo', 'Mbongo', 'Mboya', 'Mebege', 'Mebeghe', 'Mebere', 'Minga', 'Bengale', 'Minona', 'Mo',
    'Mobokomu', 'Modimo', 'Morimi', 'Moshanyana', 'Mugai', 'Mukunga', "M'bura", 'Mbura', 'Mukuru', 'Muluku', 'Mulungu',
    'Musso', 'Koroni', 'Mwambwa', 'Mwari', 'Mwuetsi', 'Naiteru', 'Kop', 'Nana', 'Buluku', 'Nasilele', 'Natero', 'Naz',
    'Ndjambi', 'Ndrian', 'Ndriananahary', 'Ndriananhary', 'Neiterkob', 'Neiternkob', 'Neiterogob', 'Ngai', 'Ngewo',
    'Wa', 'Nialith', 'Nimba', 'Ninepone', 'Njambe', 'Njambi', 'Karunga', 'Njemakati', 'Nkwa', 'Nommo', 'None', 'Nummo',
    'Nyaliep', 'Nyalitch', 'Nyambe', 'Nyambe(2)', 'Nyame', 'Nyaminyami', 'Nyankopon', 'Nyikang', 'Nyiko', 'Nyingone',
    'Nyokonan', 'Nyonye', 'Ngana', 'Nzambi', 'Nzame', 'Obaluaye', 'Obambo', 'Obambou', 'Obassi', 'Nsi', 'Osaw',
    'Obatala', 'Obatalá', 'Obàtálá', 'Ochosi', 'Ocshosi', 'Odomankomo', 'Odua', 'Odudua', 'Oduduwa', 'Oduwa', 'Odùduwà',
    'Ofo', 'Oghene', 'Ogo', 'Ogun', 'Oko', 'Olodumare', 'Olofi', 'Olokun', 'Su', 'Olokunsu', 'Olorun', 'Olufon',
    'Olurun', 'Olòrún', 'Omukuru', 'Omumborombanga', 'Omumborombonga', 'Onile', 'Onyame', 'Onyankopon', 'Orisa',
    'Orisala', 'Orisanla', 'Orisas', 'Orisha', 'Nla', 'Popo', 'Orishala', 'Orishas', 'Orixa', 'Orixas', 'Oromila',
    'Orula', 'Orunmila', 'Osanyin', 'Oshanla', 'Oshe', 'Oshun', 'Oshunmare', 'Osun', 'Oxossi', 'Oxósse', 'Iyansan',
    'Oyá', 'Pale', 'Fox', 'Pemba', 'Qamata', 'Qamta', 'Quamta', 'Raluvumbha', 'Rugaba', 'Rugira', 'Ruhanga', 'Rurema',
    'Ruwa', 'Sagbata', 'Sakarabru', 'Sakpata', 'Shadipinyi', 'Shakpana', 'Shango', 'Shankpana', 'She', 'Shonponno',
    'Soko', 'Somtup', 'Sopona', 'Soponna', 'Sudika', 'Mbambi', 'Thixo', 'Tilo', 'Tore', 'Tsetse', 'Tsui', '//goab',
    'Goab', 'Uhlanga', 'Umvelinqangi', 'Unkul', 'Unkulunkulu', 'Uthlanga', 'No', 'names', 'beginning', 'with', 'V',
    'currently', 'known', '-', 'Godchecker.com', 'Waaqa', 'Tokkichaa', 'Wak', 'Waq', 'Wele', 'Were', 'Woyengi',
    'Wulbari', 'Wuni', 'Wuona', 'Wuonji', 'Wuonkwere', 'Wuonoru', 'Xango', 'Yansan', 'Yasigi', 'Yeban', 'Yemanja',
    'Yemaya', 'Yemayah', 'Yembo', 'Yemoja', 'Yemonja', 'Yemowo', 'Yurugu', 'Zanaharibe', 'Zanahary']
