names = [
    'Abassi,', 'Abiku,', 'Abuk,', 'Achimi,', 'Adriambahomanana,', 'Adro,', 'Adroa,', 'Adroanzi,', 'Age,', 'Aha',
    'Njoku,', 'Aho', 'Njoku,', 'Aigamuxa,', 'Aje,', 'Aje', 'Shaluga,', 'Ajok,', 'Akongo,', 'Ala,', 'Ale,', 'Alla,',
    'Alouroua,', 'Amma,', 'Ananse,', 'Anansi,', 'Andriamahilala,', 'Andriambahomanani,', 'Andumbulu,', 'Ane,',
    'Anotchi,', 'Asa,', 'Atai,', 'Ataokoloinona,', 'Aunt', 'Nancy,', "Azra'il,", 'Azrail', 'Ba', 'Dimo,', 'Babalu',
    'Aye,', 'Babaluaye,', 'Babayanmi,', 'Badimo,', 'Banga,', 'Bayani,', 'Bayanni,', 'Bomazi,', 'Buk,', 'Buku,', 'Bumba',
    'Cagn,', 'Candit,', 'Cghene,', 'Chango,', 'Chedi', 'Bumba,', 'Chiuta,', 'Chonganda,', 'Chuku', 'Da,', 'Dada,',
    'Deng,', 'Ditaolane,', 'Domfe,', 'Dongo,', 'Dubiaku,', 'Dxui,', 'Dyinyinga,', 'Dziva', 'Ebore,', 'Eda,',
    'Edinkira,', 'Egungun', 'Oya,', 'Ekurana,', 'Eleduwa,', 'Elegua,', 'Elusu,', 'En', 'Kai,', 'Enekpe,', 'Engai,',
    'Enkai,', 'Eseasar,', 'Eshu,', 'Esu,', 'Evus', 'Fa,', 'Faro', 'Ga', 'Gorib,', 'Gamab,', 'Gaunab,', 'Ghekre,', 'Gu,',
    'Gunab', 'Haitse', 'Aibeb,', 'Haitsi', 'Aibeb,', 'Haiuri,', 'Hare,', 'Heitsi,', 'Heitsi', 'Eibib,', 'Huntin,',
    'Huveane,', 'Hyel,', 'Hyel', 'Taku', 'Iamanjie,', 'Ida,', 'Imana,', 'Itherther,', 'Iyakare', 'Jakuta,', 'Jok,',
    'Jok', 'Odudu,', 'Juok', 'Kaang,', 'Kabundungulu,', 'Kaka', 'Guie,', 'Kalumba,', 'Kammapa,', 'Kanu,', 'Katonda,',
    'Khakhabaisaywa,', 'Khodumodurno,', 'Khonvoum,', 'Khuzwane,', 'Kwoth', 'Le', 'Eyo,', 'Legba,', 'Lela,', 'Leza,',
    'Libanza', 'Maori,', 'Massim', 'Biambe,', 'Mawu', 'Lisa,', 'Mbaba', 'Mwanna', 'Waresa,', 'Mbere,', 'Mbokomu,',
    'Mbombo,', 'Mbongo,', 'Mboya,', 'Mebege,', 'Mebeghe,', 'Mebere,', 'Minga', 'Bengale,', 'Minona,', 'Mo', 'Dimo,',
    'Mobokomu,', 'Modimo,', 'Morimi,', 'Moshanyana,', 'Mugai,', 'Mukunga', "M'bura,", 'Mukunga', 'Mbura,', 'Mukuru,',
    'Muluku,', 'Mulungu,', 'Musso', 'Koroni,', 'Mwambwa,', 'Mwari,', 'Mwuetsi', 'Naiteru', 'Kop,', 'Nana', 'Buluku,',
    'Nasilele,', 'Natero', 'Kop,', 'Naz,', 'Ndjambi,', 'Ndrian,', 'Ndriananahary,', 'Ndriananhary,', 'Neiterkob,',
    'Neiternkob,', 'Neiterogob,', 'Ngai,', 'Ngewo', 'Wa,', 'Nialith,', 'Nimba,', 'Ninepone,', 'Ninepone', 'Mebeghe,',
    'Njambe,', 'Njambi,', 'Njambi', 'Karunga,', 'Njemakati,', 'Nkwa,', 'Nommo,', 'None,', 'None', 'Mebeghe,', 'Nummo,',
    'Nyaliep,', 'Nyalitch,', 'Nyambe,', 'Nyambe(2),', 'Nyame,', 'Nyaminyami,', 'Nyankopon,', 'Nyikang,', 'Nyiko,',
    'Nyingone', 'Mebeghe,', 'Nyokonan,', 'Nyonye', 'Ngana,', 'Nzambi,', 'Nzame,', 'Nzame', 'Mebeghe', 'Obaluaye,',
    'Obambo,', 'Obambou,', 'Obassi', 'Nsi,', 'Obassi', 'Osaw,', 'Obatala,', 'Obatalá,', 'Obàtálá,', 'Ochosi,',
    'Ocshosi,', 'Odomankomo,', 'Odua,', 'Odudu,', 'Odudua,', 'Oduduwa,', 'Oduwa,', 'Odùduwà,', 'Ofo,', 'Oghene,',
    'Ogo,', 'Ogun,', 'Oko,', 'Olodumare,', 'Olofi,', 'Olokun,', 'Olokun', 'Su,', 'Olokunsu,', 'Olorun,', 'Olufon,',
    'Olurun,', 'Olòrún,', 'Omukuru,', 'Omumborombanga,', 'Omumborombonga,', 'Onile,', 'Onyame,', 'Onyankopon,',
    'Orisa,', 'Orisala,', 'Orisanla,', 'Orisas,', 'Orisha,', 'Orisha', 'Nla,', 'Orisha', 'Popo,', 'Orishala,',
    'Orishas,', 'Orixa,', 'Orixas,', 'Oromila,', 'Orula,', 'Orunmila,', 'Osanyin,', 'Oshanla,', 'Oshe,', 'Oshun,',
    'Oshunmare,', 'Osun,', 'Oxossi,', 'Oxósse,', 'Oya,', 'Oya', 'Iyansan,', 'Oyá', 'Pale', 'Fox,', 'Pemba', 'Qamata,',
    'Qamta,', 'Quamta', 'Raluvumbha,', 'Rugaba,', 'Rugira,', 'Ruhanga,', 'Rurema,', 'Ruwa', 'Sagbata,', 'Sakarabru,',
    'Sakpata,', 'Shadipinyi,', 'Shakpana,', 'Shango,', 'Shankpana,', 'She,', 'Shonponno,', 'Soko,', 'Somtup,',
    'Sopona,', 'Soponna,', 'Sudika', 'Mbambi', 'Thixo,', 'Tilo,', 'Tore,', 'Tsetse', 'Bumba,', 'Tsui,', 'Tsui',
    '//goab,', 'Tsui', 'Goab', 'Uhlanga,', 'Umvelinqangi,', 'Unkul,', 'Unkulunkulu,', 'Uthlanga', 'No', 'names',
    'beginning', 'with', 'V', 'currently', 'known', '-', 'Godchecker.com', 'Waaqa,', 'Waaqa', 'Tokkichaa,', 'Wak,',
    'Waq,', 'Wele,', 'Were,', 'Woyengi,', 'Wulbari,', 'Wuni,', 'Wuona,', 'Wuonji,', 'Wuonkwere,', 'Wuonoru', 'Xango',
    'Yansan,', 'Yasigi,', 'Yeban,', 'Yemanja,', 'Yemaya,', 'Yemayah,', 'Yembo,', 'Yemoja,', 'Yemonja,', 'Yemowo,',
    'Yurugu', 'Zanaharibe,', 'Zanahary']
