names = [
    "A'akuluujjusi,", 'Aakuluujjusi,', 'Abaangui,', 'Achi,', 'Achiyalabopa,', 'Achomawi,', 'Adekagagwaa,', 'Adlivun,',
    'Aguara,', 'Ahayuta,', 'Ahayuta', 'Achi,', 'Ahea,', 'Ahe’A,', 'Ahmeto', 'Lela', 'Okya,', 'Aholi,', 'Ahsonnutli,',
    'Airsekui,', 'Aisoyimstan,', 'Akba', 'Atatdia,', 'Akna,', 'Aleut,', 'Alignak,', "Alk'umta'm,", "Alk'unta'um,",
    'Alkuntam,', 'Allowat', 'Sakima,', 'Alowatsakima,', 'Amala,', 'Amitolane,', 'Amotken,', 'Anarkusuga,', 'Anaye,',
    "Angak'", 'Chin', 'Mana,', 'Angak', 'Chin', 'Mana,', 'Angalkuq,', 'Angokoq,', 'Anguta,', 'Aningan,', 'Apikunni,',
    'Apisirahts,', 'Apotamkin,', 'Apoyan', 'Tachi,', 'Aqas', 'Xena', 'Xena,', 'Aqas', 'Xena', 'Xenas,', "Arnakua'gsak,",
    'Arnakuagsak,', 'Arnarquagsag,', 'Asagaya', 'Gigaei,', 'Asgaya', 'Gigagei,', 'Ataensic,', 'Ataentsic,',
    'Atahensic,', 'Atius', 'Tirawa,', 'Awanawilonais,', 'Awitelin', 'Tsta,', 'Awonawilona', 'Badger,',
    'Bakbakwalanooksiwae,', 'Baxbakualanuchsiwae,', 'Beaver,', 'Begocidi,', 'Big', 'Head,', 'Big', 'Rabbit,', 'Bikeh',
    'Hozho,', 'Binaye', 'Ahani,', 'Black', 'God,', 'Blue', 'Jay,', 'Bokwus,', 'Bototo', 'Capa,', 'Chacomat,',
    'Chacopa,', 'Chakekenapok,', 'Chehooit,', 'Chibiabos,', 'Chinigchinich,', 'Chipiapoos,', 'Chulyen,', 'Copper',
    'Woman,', 'Corn', 'Maidens,', 'Corn', 'Mother,', 'Corn', 'Woman,', 'Coyote,', 'Crow', 'Dajoji,', 'Dawn,',
    'Dayunsi,', 'Dew', 'Eagle,', 'Dohkwibuhch,', 'Doquebuth,', 'Dzalarhons,', 'Dzelarhons,', 'Dzoavits', 'Eeyeekalduk,',
    'Ehlaumel,', 'Eithinoha,', 'Enumclaw,', 'Eototo,', 'Esaugetuh', 'Emissee,', 'Estanatlehi,', 'Estasanatlehi,',
    'Estsanatlehi,', 'Ewah', 'First', 'Scolder,', 'Flying', 'Head', "Ga'an,", 'Ga', 'Gaah,', 'Ga', 'Oh,', 'Gaan,',
    'Gahe,', 'Gaoh,', 'Gendenwitha,', 'Gendewitha,', 'Gitche', 'Manito,', 'Gitche', 'Manitou,', 'Gitchi', 'Manitou,',
    'Gitchie', 'Manitou,', 'Gitsche', 'Manitou,', 'Glooscap,', 'Glooskap,', 'Gluscabe,', 'Gluscabi,', 'Gluskab,',
    'Gluskabe,', 'Gluskap,', 'Grandmother', 'Corn,', 'Great', 'Hare,', 'Great', 'Head,', 'Great', 'Rabbit,',
    'Gudratrigakwitl,', 'Guguyni,', 'Gunnodayak,', 'Gyhldeptis', 'Hahgwehdaetgah,', 'Hahgwehdiyu,', 'Haokah,',
    'Hastseoltoi,', 'Hastshehogan,', 'Hayicanako,', 'Hemaskas,', 'Hino,', 'Hinu,', 'Hinun,', 'Hisagita', 'Imisi,',
    'Hisagitaimisi,', 'Hisakitaimisi,', 'Human', 'Maker,', 'Humanmaker,', 'Huruing', 'Wuhti', 'Ibofanga,', 'Ictinike,',
    'Igaluk,', 'Ignirtoq,', 'Ikto,', 'Iktomi,', 'Inktomi,', 'Ioi,', 'Ioskeha,', 'Irdlirvirisissong,', 'Isitoq,',
    'Issitoq,', 'Iya,', 'Iyatiku', 'Kachinas,', 'Kaiti,', 'Kananeski', 'Anayehi,', 'Kanati,', 'Kapoonis,', 'Karwan,',
    "Kat'sinas,", 'Kioskurber,', 'Kitche', 'Manitou,', 'Kitchi', 'Manitou,', 'Kitshi', 'Manitou,', 'Kivati,',
    'Kloskurbeh,', 'Koko,', 'Kokopelli,', 'Kokyangwuti,', 'Koshere,', 'Koyangwuti,', 'Koyemsi,', 'Kumokum,', 'Kumush,',
    'Kushapatshikan,', 'Kutnahin,', 'Kwa', 'Kwakalanooksiwae,', 'Kwakwakalanooksiwae,', 'Kwatee,', 'Kwatyat,',
    "Kwekwaxa'we,", 'Kwekwaxawe,', 'Kwikumat,', 'Kwikwilyaqa', 'Logobola', 'Magician,', 'Maheo,', 'Malsum,',
    'Malsumis,', 'Malsun,', 'Mana,', 'Manabozho,', 'Manabozo,', 'Manabush,', 'Manibozho,', 'Manidoog,', 'Manidoowag,',
    'Manisar,', 'Manit,', 'Manito,', 'Manitoa,', 'Manitoo,', 'Manitou,', 'Manitu,', 'Mantóac,', 'Marten,', 'Michabo,',
    'Mising,', 'Moar,', 'Momo,', 'Mudhead,', 'Muskrat', "Na'pi,", 'Nagaitcho,', 'Nanabozho,', 'Nanabozo,',
    "Nankil'slas,", 'Nanook,', 'Napi,', 'Nataska,', 'Nayanezgani,', 'Negafook,', 'Nerivik,', 'Nerrivik,', 'Nipinoukhe,',
    'Nocoma,', 'Nokomis,', 'Nokomos,', 'Nootaikok,', 'Nukatem,', 'Nuliajuk,', 'Nunuso', 'Ocasta,', 'Odzihozo,', 'Old',
    'Man,', 'Old', 'Man', 'Coyote,', 'Olelbis,', 'Ololowishkya,', 'Onatah,', 'Oshadagea,', 'Otter,', 'Owiot', 'Pah,',
    'Palhik', 'Mana,', 'Pamit,', 'Payatamu,', 'Pipinoukhe,', 'Poia,', 'Poshaiyankayo,', 'Pukkeenegak',
    "Qa'wadliliquala,", 'Qamaits,', 'Qawadliliquala,', 'Quaayayp,', 'Quaoar', 'Raven,', 'Rhpisunt', 'Sanopi,', 'Sedit,',
    'Sedna,', 'Selu,', 'Senx,', 'Shakaru,', 'Shakuru,', 'Siarnaq,', 'Sint', 'Holo,', 'Sisiutl,', 'Skan,', 'Skili,',
    'Snoqalm,', 'Snoqualm,', 'Sosondowah,', 'Sotuknang,', 'Spider', 'Grandmother,', 'Spider', 'Woman,',
    'Sussistanako,', 'Szeukha', 'Tabaldak,', 'Taiowa,', 'Tamit,', 'Tarhuhyiawahku,', 'Tawiskara,', 'Tekkeitserktock,',
    'Ten', 'Corn', 'Maidens,', "Tewi'xilak,", 'Tewixilak,', 'Theelgeth,', 'Thelgeth,', 'Thunder', 'Bird,', 'Thunder',
    'Twins,', 'Thunderbird,', 'Tihtipihin,', 'Tirawa,', 'Tirawa', 'Atius,', 'Tobadzistsini,', 'Tolmalok,', 'Tonenili,',
    'Tornarsuk,', 'Torngarsak,', 'Torngasak,', 'Torngasoak,', 'Totem', 'Poles,', 'Tsohanoai,', 'Tukupar', 'Itar,',
    'Twin', 'Brothers,', 'Txamsem', 'Umai', 'Hulhlya', 'Wit,', 'Umai', 'Hulhya', 'Wit,', 'Uncegila,', 'Underwater',
    'Panthers,', 'Unelanuki,', 'Unktehi,', 'Unktome,', 'Untunktahe,', 'Utset', 'Wabasso,', 'Wabosso,', 'Wakan',
    'Tanka,', 'Wakanda,', 'Wakinyan,', 'Wakonda,', 'Waukheon,', 'We', 'Gyet,', 'Wenabozho,', 'Wendego,', 'Wendigo,',
    'Wetiko,', 'Weywot,', 'Wheemeemeowah,', 'Wheememeowah,', 'White', 'Buffalo', 'Woman,', 'White', 'She', 'Buffalo,',
    'Winabozho,', 'Windago,', 'Windego,', 'Windikouk,', 'Wisaaka,', 'Wishpoosh,', 'Wonomi', 'Xelas', 'Yhel']
