names = [
    'Abandinus,', 'Abarta,', 'Abred,', 'Achren,', 'Aebh,', 'Aed,', 'Aengus,', 'Aeron?,', 'Afagddu,', 'Agrona,', 'Ai,',
    'Ai', 'Mac', 'Ollamon,', 'Aibell,', 'Aichleach,', 'Aife,', 'Ailbe,', 'Ailill', 'Anglonnach,', 'Ailill', 'Mac',
    'Mata,',
    'Ailill', 'Olom,', 'Aille,', 'Aillen,', 'Aillinn,', 'Aimend,', 'Aine,', 'Ainge,', 'Airmid,', 'Alisanos,',
    'Amaethon,',
    'Amairgen,', 'Amairgin,', 'Amathaon,', 'Ana,', 'Andarta,', 'Andraste,', 'Angau,', 'Angus', 'Óg,', 'Ankou,',
    'Anluan,',
    'Annwfn,', 'Annwn,', 'Anociticus,', 'Antenociticus,', 'Anu,', 'Aobh,', 'Aoife,', 'Aonghus,', 'Araius,', 'Aranrhod,',
    'Arawn,', 'Arbeth,', 'Arca', 'Dubh,', 'Arduinna,', 'Argetlámh,', 'Arianrhod,', 'Arianrod,', 'Arionrod,',
    'Arnemetia,',
    'Art', 'Mac', 'Cuinn,', 'Artaios,', 'Artaius,', 'Arthur,', 'Artio,', 'Assal,', 'Aywell', 'Badb,', 'Badbh,',
    'Balaticaurus,', 'Balatocadrus,', 'Balatucadrus,', 'Baliticaurus,', 'Balor,', 'Banba,', 'Banshee,', 'Bean', 'Sí,',
    'Bean', 'Sídhe,', 'Bean', 'Nighe,', 'Bebhionn,', 'Bebinn,', 'Bec', 'Mac', 'Buainn,', 'Bel,', 'Belatucadros,',
    'Belatucairus,', 'Belatugagus,', 'Belenus,', 'Beli,', 'Beli', 'Mawr,', 'Belinos,', 'Belisama,', 'Beliticaurus,',
    'Beltaine,', 'Belus,', 'Benadonner,', 'Benandonner,', 'Birog,', 'Blathnat,', 'Blatucadrus,', 'Blatucairus,',
    'Blodeuedd,', 'Bláithéne,', 'Bláthnad,', 'Bláthíne,', 'Boann,', 'Bobd', 'Derg,', 'Bodb', 'Dearg,', 'Bodb', 'the',
    'Red,', 'Bodhb', 'Dearg,', 'Bormana,', 'Bormanna,', 'Bormanus,', 'Bormo,', 'Borvo,', 'Bove', 'Derg,', 'Bran,',
    'Bran',
    'the', 'Blessed,', 'Branwen,', 'Bres,', 'Brian,', 'Bricriu,', 'Bricriu', 'Nemthenga,', 'Brigantia,', 'Brigid,',
    'Brigit,', 'Brounie,', 'Brownie,', 'Brughna', 'Boinne,', 'Brían,', 'Brùnaidh,', 'Buanann,', 'Buggane,', 'Bwbach,',
    'Bwbachod', '(Plural),', 'Bwca,', 'Bébhinn,', 'Bíle,', 'Bóand,', 'Bóinn', 'Cael,', 'Caer,', 'Caibell,', 'Cailitin,',
    'Cailleach,', 'Cailleach', 'Beara,', 'Cailleach', 'Bheur,', 'Caillech,', 'Cailliach,', 'Callech,', 'Cally',
    'Berry,',
    'Camulos,', 'Camulus,', 'Cano,', 'Cano', 'Mac', 'Gartnáin,', 'Caradog,', 'Caridwen,', 'Carldwen,', 'Carman,',
    'Carme,',
    'Carmun,', 'Caswallon,', 'Cathbad,', 'Cathbhadh,', 'Cathubodua,', 'Cathubodva,', 'Catubodua,', 'Celtchair,', 'Cenn',
    'Cruach,', 'Ceridwen,', 'Cernunnos,', 'Cernunnus,', 'Cerridwyn,', 'Cethern', 'Mac', 'Fintain,', 'Cetshamhain,',
    'Ceugant,', 'Changeling,', 'Ciabhan,', 'Cian,', 'Cigfa,', 'Cleena,', 'Cliodhna,', 'Clionadh,', 'Clota,', 'Clud,',
    'Clídna,', 'Cocidius,', 'Coincheann,', 'Coinchenn,', 'Conall,', 'Conan,', 'Conaran,', 'Condatis,', 'Conlai,',
    'Conn',
    'Cetchathach,', 'Connla,', 'Conán', 'the', 'Bald,', 'Credne,', 'Creirwy,', 'Crom', 'Cruaich,', 'Crom', 'Crúaich,',
    'Crom', 'Dubh,', 'Cromm', 'Cruach,', 'Crunniuc,', 'Cu', 'Chulainn,', 'Cu', 'Roi,', 'Cuchulainn,', 'Culann,',
    'Cumhall,', 'Cáer', 'Ibormeith', 'Da', 'Derga,', 'Dagda,', 'Dagdha,', 'Daire,', 'Daire', 'Mac', 'Fiachna,',
    'Damona,',
    'Dana,', 'Danu,', 'Dechtire,', 'Dechtiré,', 'Deirdre,', 'Delbchaem,', 'Dewi,', 'Dian,', 'Dian', 'Cecht,',
    'Diarmait,',
    'Dirona,', 'Domnu,', 'Don,', 'Donn,', 'Donn', 'Cuailnge,', 'Dubh,', 'Dubh', 'Lacha,', 'Dubhthach', 'Doeltenga,',
    'Dylan,', 'Dylan', 'Eil', 'Ton', 'Echdae,', 'Ecne,', 'Efnisien,', 'Eithne,', 'Elatha,', 'Elffin,', 'Emain',
    'Ablach,',
    'Emer,', 'Eochaid', 'Ollathair,', 'Epona,', 'Eriu,', 'Esus,', 'Etain,', 'Etheline,', 'Ethlinn,', 'Evnissyen',
    'Fand,',
    'Fea,', 'Fear', 'Doirche,', 'Fer', 'Doirich,', 'Findbhair,', 'Finegas,', 'Finn', 'Maccoul,', 'Finn', 'Mccool,',
    'Finn',
    'Maccool,', 'Fintan,', 'Fionn', 'Mac', 'Cumhaill,', 'Firbolg,', 'Fodla,', 'Fomoire,', 'Fomorii,', 'Formorians,',
    'Fotla,', 'Fraoch,', 'Fuamnach,', 'Fódhla,', 'Fótla', 'Goibhniu,', 'Goibniu,', 'Grannos,', 'Grannus,', 'Gwen',
    'Bach,',
    'Gwion', 'Bach,', 'Gwri,', 'Gwyddion,', 'Gwydion', 'Herne', 'Icovellauna,', 'Ildánach,', 'Irusan', 'Ler,', 'Lir,',
    'Lleu,', 'Lleu', 'Llaw', 'Gyffes,', 'Llwyd,', 'Llyr,', 'Lug,', 'Lugh,', 'Lugus', 'Mabon,', 'Mac', 'Ind', 'Óg,',
    'Mac',
    'Óg,', 'Mac', 'Cecht,', 'Macha,', 'Maeve,', 'Maga,', 'Manannan', 'Maclir,', 'Manannán', 'Mac', 'Lir,', 'Manawydan,',
    'Maponos,', 'Math,', 'Matunus,', 'Medb,', 'Merlin,', 'Midir,', 'Mil,', 'Mile,', 'Milesius,', 'Mm,', 'Mongan,',
    'Morfran,', 'Morrigan,', 'Morrighan,', 'Morrigna,', 'Morrigu', 'Nantosueta,', 'Nantosuetta,', 'Nantosvelta,',
    'Nechtan,', 'Nemain,', 'Nemglan,', 'Niamh,', 'Nodens,', 'Nuada,', 'Nuada', 'Argatlam,', 'Nudd', 'Oenghus,',
    'Oghma,',
    'Ogma,', 'Ogmios,', 'Ogmious,', 'Ogmius,', 'Oisin,', 'Ossian', 'Pryderi,', 'Pwyll', 'Rhiannon,', 'Rosmerta,',
    'Ruadan',
    'Sadb,', 'Sadhbh,', 'Salmon', 'of', 'Knowledge,', 'Sheela', 'Na', 'Gig,', 'Sirona,', 'Succellos,', 'Sucellos,',
    'Sucellus,', 'Sétanta', 'Tailtu,', 'Taliesin,', 'Taranis,', 'Tegid', 'Foel,', 'Teutatis,', 'The', 'Dark', 'Druid,',
    'The', 'Dark', 'Fairy,', 'The', 'Dark', 'Man,', 'The', 'Red', 'Man,', 'Tuatha', 'De', 'Danann,', 'Tuatha', 'Dé',
    'Danann,', 'Twrch', 'Tryth,', 'Téthur', 'Urisk,', 'Uruisg', 'Washer', 'At', 'the', 'Ford,', 'Washer', 'Woman,',
    'Wogan', 'Xulsigiae', 'Ábartach', 'Éire,', 'Étain']
