names = [
    'Abandinus', 'Abarta', 'Abred', 'Achren', 'Aebh', 'Aed', 'Aengus', 'Aeron?', 'Afagddu', 'Agrona', 'Ai', 'Mac',
    'Ollamon', 'Aibell', 'Aichleach', 'Aife', 'Ailbe', 'Ailill', 'Anglonnach', 'Mata', 'Olom', 'Aille', 'Aillen',
    'Aillinn', 'Aimend', 'Aine', 'Ainge', 'Airmid', 'Alisanos', 'Amaethon', 'Amairgen', 'Amairgin', 'Amathaon', 'Ana',
    'Andarta', 'Andraste', 'Angau', 'Angus', 'Óg', 'Ankou', 'Anluan', 'Annwfn', 'Annwn', 'Anociticus', 'Antenociticus',
    'Anu', 'Aobh', 'Aoife', 'Aonghus', 'Araius', 'Aranrhod', 'Arawn', 'Arbeth', 'Arca', 'Dubh', 'Arduinna', 'Argetlámh',
    'Arianrhod', 'Arianrod', 'Arionrod', 'Arnemetia', 'Art', 'Cuinn', 'Artaios', 'Artaius', 'Arthur', 'Artio', 'Assal',
    'Aywell', 'Badb', 'Badbh', 'Balaticaurus', 'Balatocadrus', 'Balatucadrus', 'Baliticaurus', 'Balor', 'Banba',
    'Banshee', 'Bean', 'Sí', 'Sídhe', 'Nighe', 'Bebhionn', 'Bebinn', 'Bec', 'Buainn', 'Bel', 'Belatucadros',
    'Belatucairus', 'Belatugagus', 'Belenus', 'Beli', 'Mawr', 'Belinos', 'Belisama', 'Beliticaurus', 'Beltaine',
    'Belus', 'Benadonner', 'Benandonner', 'Birog', 'Blathnat', 'Blatucadrus', 'Blatucairus', 'Blodeuedd', 'Bláithéne',
    'Bláthnad', 'Bláthíne', 'Boann', 'Bobd', 'Derg', 'Bodb', 'Dearg', 'the', 'Red', 'Bodhb', 'Bormana', 'Bormanna',
    'Bormanus', 'Bormo', 'Borvo', 'Bove', 'Bran', 'Blessed', 'Branwen', 'Bres', 'Brian', 'Bricriu', 'Nemthenga',
    'Brigantia', 'Brigid', 'Brigit', 'Brounie', 'Brownie', 'Brughna', 'Boinne', 'Brían', 'Brùnaidh', 'Buanann',
    'Buggane', 'Bwbach', 'Bwbachod', '(Plural)', 'Bwca', 'Bébhinn', 'Bíle', 'Bóand', 'Bóinn', 'Cael', 'Caer', 'Caibell',
    'Cailitin', 'Cailleach', 'Beara', 'Bheur', 'Caillech', 'Cailliach', 'Callech', 'Cally', 'Berry', 'Camulos',
    'Camulus', 'Cano', 'Gartnáin', 'Caradog', 'Caridwen', 'Carldwen', 'Carman', 'Carme', 'Carmun', 'Caswallon',
    'Cathbad', 'Cathbhadh', 'Cathubodua', 'Cathubodva', 'Catubodua', 'Celtchair', 'Cenn', 'Cruach', 'Ceridwen',
    'Cernunnos', 'Cernunnus', 'Cerridwyn', 'Cethern', 'Fintain', 'Cetshamhain', 'Ceugant', 'Changeling', 'Ciabhan',
    'Cian', 'Cigfa', 'Cleena', 'Cliodhna', 'Clionadh', 'Clota', 'Clud', 'Clídna', 'Cocidius', 'Coincheann', 'Coinchenn',
    'Conall', 'Conan', 'Conaran', 'Condatis', 'Conlai', 'Conn', 'Cetchathach', 'Connla', 'Conán', 'Bald', 'Credne',
    'Creirwy', 'Crom', 'Cruaich', 'Crúaich', 'Cromm', 'Crunniuc', 'Cu', 'Chulainn', 'Roi', 'Cuchulainn', 'Culann',
    'Cumhall', 'Cáer', 'Ibormeith', 'Derga', 'Dagda', 'Dagdha', 'Daire', 'Fiachna', 'Damona', 'Dana', 'Danu',
    'Dechtire', 'Dechtiré', 'Deirdre', 'Delbchaem', 'Dewi', 'Dian', 'Cecht', 'Diarmait', 'Dirona', 'Domnu', 'Don',
    'Donn', 'Cuailnge', 'Lacha', 'Dubhthach', 'Doeltenga', 'Dylan', 'Eil', 'Ton', 'Echdae', 'Ecne', 'Efnisien',
    'Eithne', 'Elatha', 'Elffin', 'Emain', 'Ablach', 'Emer', 'Eochaid', 'Ollathair', 'Epona', 'Eriu', 'Esus', 'Etain',
    'Etheline', 'Ethlinn', 'Evnissyen', 'Fand', 'Fea', 'Fear', 'Doirche', 'Doirich', 'Findbhair', 'Finegas', 'Finn',
    'Maccoul', 'Mccool', 'Maccool', 'Fintan', 'Fionn', 'Cumhaill', 'Firbolg', 'Fodla', 'Fomoire', 'Fomorii',
    'Formorians', 'Fotla', 'Fraoch', 'Fuamnach', 'Fódhla', 'Fótla', 'Goibhniu', 'Goibniu', 'Grannos', 'Grannus', 'Gwen',
    'Bach', 'Gwion', 'Gwri', 'Gwyddion', 'Gwydion', 'Herne', 'Icovellauna', 'Ildánach', 'Irusan', 'Ler', 'Lir', 'Lleu',
    'Llaw', 'Gyffes', 'Llwyd', 'Llyr', 'Lug', 'Lugh', 'Lugus', 'Mabon', 'Ind', 'Macha', 'Maeve', 'Maga', 'Manannan',
    'Maclir', 'Manannán', 'Manawydan', 'Maponos', 'Math', 'Matunus', 'Medb', 'Merlin', 'Midir', 'Mil', 'Mile',
    'Milesius', 'Mm', 'Mongan', 'Morfran', 'Morrigan', 'Morrighan', 'Morrigna', 'Morrigu', 'Nantosueta', 'Nantosuetta',
    'Nantosvelta', 'Nechtan', 'Nemain', 'Nemglan', 'Niamh', 'Nodens', 'Nuada', 'Argatlam', 'Nudd', 'Oenghus', 'Oghma',
    'Ogma', 'Ogmios', 'Ogmious', 'Ogmius', 'Oisin', 'Ossian', 'Pryderi', 'Pwyll', 'Rhiannon', 'Rosmerta', 'Ruadan',
    'Sadb', 'Sadhbh', 'Salmon', 'of', 'Knowledge', 'Sheela', 'Na', 'Gig', 'Sirona', 'Succellos', 'Sucellos', 'Sucellus',
    'Sétanta', 'Tailtu', 'Taliesin', 'Taranis', 'Tegid', 'Foel', 'Teutatis', 'The', 'Dark', 'Druid', 'Fairy', 'Tuatha',
    'De', 'Danann', 'Dé', 'Twrch', 'Tryth', 'Téthur', 'Urisk', 'Uruisg', 'Washer', 'At', 'Ford', 'Wogan', 'Xulsigiae',
    'Ábartach', 'Éire', 'Étain']
