names = [
    'Aah', 'Aapep', 'Abtu', 'Ahemait', 'Ahti', 'Ailuros', 'Aken', 'Aker', 'Amathaunta', 'Amaunet', 'Amemait', 'Amen',
    'Ra', 'Re', 'Amenhotep', 'Ament', 'Amentet', 'Amentit', 'Ammam', 'Ammit', 'Ammon', 'Ammut', 'Amn', 'Amon', 'Amsit',
    'Amun', 'Anat', 'Andjety', 'Anedjti', 'Anet', 'Anezti', 'Anhur', 'Anit', 'Ankh', 'Ankhet', 'Ankt', 'Anouke', 'Anpu',
    'Anti', 'Anubis', 'Anuket', 'Apademak', 'Apedemak', 'Apep', 'Apepi', 'Apet', 'Apis', 'Apophis', 'Aptet',
    'Arensnuphis', 'Ari', 'Hes', 'Nefer', 'Arsnuphis', 'Aset', 'Aten', 'Aton', 'Atum', 'Neb', 'Tetet', 'Pef', 'Bab',
    'Babay', 'Babi', 'Baneb', 'Djedet', 'Banebdedet', 'Banebdjedet', 'Banebdjetet', 'Banebtetet', 'Banephthysdjedet',
    'Bast', 'Bastet', 'Bat', 'Bata', 'Benu', 'Bes', 'Beset', 'Book', 'Dead', 'Buto', 'Chenti', 'Cheti', 'Irti',
    'Chepri', 'Cherti', 'Chnemu', 'Chnoumis', 'Chnum', 'Chnuphis', 'Chons', 'Chontamenti', 'Cneph', 'Dedun', 'Dedwen',
    'Dua', 'Duamutef', 'Ehi', 'Ernutet', 'Geb', 'Ha', 'Haap', 'Hah', 'Hap', 'Hapakhered', 'Hapi', 'Hapy', 'Har', 'Nedj',
    'Hef', 'Pa', 'Khered', 'Khruti', 'Harensnuphis', 'Harmakhis', 'Harmatchis', 'Haroeris', 'Harpakhered',
    'Harpakhruti', 'Hat', 'Mehit', 'Hathor', 'Hatmehit', 'Hatmehyt', 'Hauhet', 'Hedetet', 'Heget', 'Heh', 'Hehet',
    'Hek', 'Heka', 'Heket', 'Hektet', 'Hemen', 'Hemsut', 'Hemuset', 'Henet', 'Hep', 'Hepi', 'Heptet', 'Heqet', 'Heret',
    'Herishep', 'Heru', 'Behudti', 'Hesa', 'Hesat', 'Het', 'Hetmehit', 'Hez', 'Ur', 'Hike', 'Horus', 'Hu', 'Huh', 'Iah',
    'Djuhty', 'Iat', 'Ibis', 'Ienpw', 'Ihu', 'Ihy', 'Imentet', 'Imeut', 'Imhetep', 'Imhotep', 'Imiut', 'Imset',
    'Imsety', 'Inher', 'Inmutef', 'Inpu', 'Ipet', 'Iptet', 'Ipy', 'Isis', 'Iunmutef', 'Jah', 'Joh', 'Ka', 'Kauket',
    'Keb', 'Kebechet', 'Kebechsenef', 'Kehperi', 'Kek', 'Keket', 'Keku', 'Kemu', 'Kemur', 'Kemwer', 'Ken', 'Khem',
    'Khensu', 'Kheper', 'Khepera', 'Khepra', 'Khepri', 'Kherty', 'Khnemu', 'Khnum', 'Khons', 'Khonsu', 'Kneph',
    'Knouphis', 'Knum', 'Kuk', 'Lenpw', "Ma'at", 'Maat', 'Mafdet', 'Maftet', 'Mahes', 'Mehen', 'Mehet', 'Uret', 'Weret',
    'Mehturt', 'Mehurt', 'Menchit', 'Mendes', 'Menhit', 'Menthu', 'Mentu', 'Menu', 'Meret', 'Meretseger', 'Mert',
    'Mertseger', 'Meskhenet', 'Meskhent', 'Min', 'Mnevis', 'Mnewer', 'Month', 'Monto', 'Mut', 'Naunet', 'Hut',
    'Nebthet', 'Ned', 'Er', 'Tcher', 'Nef', 'Tem', 'Temu', 'Nefertem', 'Nefertum', 'Nehab', 'Nehebkau', 'Nehebkhau',
    'Nehebu', 'Kau', 'Neit', 'Neith', 'Nekhabed', 'Nekhbet', 'Neper', 'Nephthys', 'Nepit', 'Neteraantmwmw', 'Nu',
    'Nuit', 'Nun', 'Nunet', 'Nut', 'Ogdoad', 'Onuris', 'Opet', 'Osiris', 'Petbe', 'Ptah', 'Ptha', 'Qadesh', 'Qadeshet',
    'Qeb', 'Qetesh', 'Qudshu', 'Renenet', 'Renenutet', 'Renpet', 'Reret', 'Reshep', 'Reshpu', 'Sachmet', 'Sag', 'Sahu',
    'Sakhmet', 'Sal', 'Satet', 'Seb', 'Sebek', 'Seker', 'Sekhet', 'Sekhmet', 'Selket', 'Selkit', 'Sep', 'Sepa', 'Septu',
    'Serket', 'Serquet', 'Seshat', 'Sesmu', 'Set', 'Setekh', 'Setesh', 'Seth', 'Seti', 'Sešat', 'Shai', 'Shait', 'Shay',
    'Shed', 'Shenty', 'Shesmetet', 'Shu', 'Sobek', 'Sochet', 'Sokar', 'Sokaris', 'Soker', 'Sons', 'Sopd', 'Sopdet',
    'Sopdu', 'Sopedu', 'Sothis', 'Sphinx', 'Suchos', 'Sutekh', 'Tahuti', 'Tatenen', 'Taueret', 'Taurt', 'Taweret',
    'Tefen', 'Tefenet', 'Tefnet', 'Tefnut', 'Tehuti', 'Thoeris', 'Thot', 'Thoth', 'Thureris', 'Toeris', 'Tphenis',
    'Tum', 'Tutu', 'Uadjet', 'Ubastet', 'Un', 'Uneg', 'Unut', 'Usire', 'Wadj', 'Wer', 'Wadjet', 'Waset', 'Wenut',
    'Wepawet', 'Wosret', 'Wosyet', 'Yah', 'Yinepu', 'Šu']
