# -*- coding: utf-8 -*-
names = [
    'Aditi', 'Adityas', 'Adivaraha', 'Agastya', 'Agastyar', 'Agathiar', 'Agni', 'Ambika', 'Amitabha', 'Ammavaru',
    'Amrita', 'Ananda', 'Angiras', 'Angirasa', 'Anjana', 'Annapurna', 'Ansa', 'Anumati', 'Anuradha', 'Apsaras',
    'Aranyani', 'Ardhanarishvara', 'Ardra', 'Arjuna', 'Aruna', 'Arundhati', 'Aryaman', 'Aryman', 'Ashvathaman',
    'Ashvins', 'Ashwathama', 'Ashwatthama', 'Aslesa', 'Asuras', 'Asvins', 'Atri', 'Avalokitesvara', 'Avatar',
    'Ayyappan', 'Balaji', 'Balarama', 'Bali', 'Balin', 'Bhadra', 'Bhaga', 'Bhagiratha', 'Bharani', 'Bharati', 'Bhavani',
    'Bhima', 'Bhisma', 'Bhutamata', 'Bhutas', 'Bodhisattva', 'Bodhisattvas', 'Brahma', 'Brahman', 'Brighu', 'Brighus',
    'Brihaspati', 'Buddha', 'Budha', 'Candra', 'Candramus', 'Chaitany', 'Chamunda', 'Chandanayika', 'Chandra',
    'Chinnamastaka', 'Chitragputas', 'Daityas', 'Dakini', 'Daksa', 'Daksha', 'Dakshesha', 'Deva', 'Devadatta', 'Devaki',
    'Devas', 'Devi', 'Devis', 'Dhanistha', 'Dhanvantari', 'Dhara', 'Dharani', 'Dharma', 'Dhatar', 'Dhati', 'Dhatri',
    'Dhritarashtra', 'Dhruva', 'Diti', 'Draupathi', 'Durga', 'Durgha', 'Duryodhana', 'Dyaus', 'Dyavaprivithi',
    'Eightfold', 'Path', 'Way', 'Gandharvas', 'Ganesh', 'Ganesha', 'Ganga', 'Garuda', 'Gauri', 'Gautama', 'Maharishi',
    'Gommateshvara', 'Hanuman', 'Hara', 'Hari', 'Harihara', 'Hariti', 'Haritiki', 'Hayagriva', 'Himavat',
    'Hiranyakashipu', 'Hiranyakasipu', 'Hiranyaksha', 'Indra', 'Indrani', 'Jagganath', 'Jalandhara', 'Jambavan',
    'Jambavat', 'Jara', 'Jatayu', 'Juggernaut', 'Kadru', 'Kaduvul', 'Kalanemi', 'Kali', 'Kalki', 'Kama', 'Kamadhenu',
    'Kamsa', 'Kansa', 'Karni', 'Karttireya', 'Kasyapa', 'Katavul', 'Katukilal', 'Kauravas', 'Kausalya', 'Kaushika',
    'Kinnaras', 'Kistnerappan', 'Korrawi', 'Kratu', 'Krishna', 'Kubera', 'Kumbhakarna', 'Kundalini', 'Kunti', 'Kurma',
    'Lakshmana', 'Lakshmi', 'Laksmi', 'Lokapalas', 'Machilottu', 'Madri', 'Madya', 'Mahakala', 'Maithuna', 'Maitreya',
    'Manasa', 'Mandala', 'Mansa', 'Manu', 'Mara', 'Marichi', 'Marishi', 'Maruts', 'Matsya', 'Meru', 'Mitra', 'Mmmmm',
    'Muchalinda', 'Mudra', 'Murukan', 'Nagas', 'Naginas', 'Nakula', 'Nandhini', 'Nandi', 'Nandin', 'Nandini', 'Nandisa',
    'Narada', 'Narasimha', 'Narasingh', 'Narasinha', 'Nirrita', 'Nirriti', 'Nirritu', 'Nirvana', 'Pancika', 'Pandavas',
    'Pandu', 'Pangika', 'Panjika', 'Parashurama', 'Parjanya', 'Parvati', 'Pañcika', 'Pisakas', 'Prahlada', 'Prajapati',
    'Prajapatis', 'Prisni', 'Privithi', 'Prthivi', 'Pulaha', 'Pulastja', 'Pulastya', 'Purusha', 'Pushan', 'Pushpaka',
    'Putana', 'Rahu', 'Rakshasas', 'Rama', 'Rati', 'Ratri', 'Ravana', 'Rhibus', 'Ribhus', 'Rig', 'Veda', 'Rishi',
    'Rishis', 'Rohini', 'Rshis', 'Rudra', 'Rudrani', 'Rudras', 'Rukmini', 'Sadhyas', 'Sagara', 'Sahadeva', 'Saktassura',
    'Sakti', 'Salaka', 'Purusas', 'Salakapurusas', 'Samba', 'Sapta', 'Saptarishis', 'Saranyu', 'Sarasvati', 'Saraswati',
    'Sati', 'Savitri', 'Shakti', 'Shakyamuni', 'Shasti', 'Shatrughma', 'Shatrughna', 'Shesha', 'Shitala', 'Shiva',
    'Shri', 'Siddharta', 'Siddhartha', 'Sisupala', 'Sita', 'Skanda', 'Soma', 'Sri', 'Sugriva', 'Sumeru', 'Sumitra',
    'Surabhi', 'Surya', 'Tara', 'Taraka', 'Tastar', 'Tataka', 'Thataka', 'Tirthankaras', 'Trimurti', 'Trinavarta',
    'Trisastisalakapurusa', 'Tvashtri', 'Tvastar', 'Tārakā', 'Tārā', 'Ugrasena', 'Uma', 'Upanishads', 'Urvashi',
    'Ushas', 'Vach', 'Vajrapani', 'Vali', 'Vamana', 'Vanadevatas', 'Varaha', 'Varuna', 'Varuni', 'Vashishta',
    'Vashishtha', 'Vasishtha', 'Vasistha', 'Vasudevas', 'Vasuki', 'Vasus', 'Vayu', 'Vedas', 'Venkateswari', 'Vibishana',
    'Vinata', 'Viraj', 'Virupaksa', 'Vishnu', 'Vishvakarman', 'Vishvamitra', 'Vishwamitra', 'Vitra', 'Vivasat',
    'Vritra', 'Vāsudevas', 'Yab', 'Yum', 'Yakshas', 'Yama', 'Yamuna', 'Yashas', 'Yashoda', 'Yashodhara', 'Yasoda',
    'Yudhishthira']
