# -*- coding: utf-8 -*-
names = [
    'Ac', 'Yanto', 'Acan', 'Acantuns', 'Acat', 'Ah', 'Bolom', 'Tzacab', 'Bolon', "Dz'acab", 'Dzacab', 'Chicum', 'Ek',
    'Chicumek', 'Ciliz', 'Cuxtal', 'Hoya', 'Hulneb', 'Kin', 'Kinchil', 'Mucen', 'Cab', 'Muzen', 'Muzencab', 'Peku',
    'Puch', 'Tzenul', 'Tzul', 'Uuk', 'Yol', 'Zip', 'Ahau', 'Ahpuch', 'Akbul', 'Alaghom', 'Naom', 'Tzentel', 'Alphabet',
    'Gods', 'Bacab', 'Bacabs', 'Backlum', 'Chaam', 'Balam', 'Balams', 'Balanque', 'Becabs', 'Belachina', 'Elaba',
    'Beydo', 'Ti', 'Ku', 'Tiku', 'Tzakab', 'Bolontiku', 'Bulkabil', 'Buluc', 'Chabtan', 'Buluk', 'Kab', 'Cabracan',
    'Cabrakan', 'Cacoch', 'Cakulha', 'Cama', 'Zotz', 'Camazotz', 'Can', 'Tzicnal', 'Caneques', 'Cantzicnal', 'Cauac',
    'Chaac', 'Chaak', 'Chel', 'Mol', 'Mool', 'Uayeb', 'Xoc', 'Xib', 'Chacmool', 'Chak', 'Chaob', 'Chibilkin', 'Chiccan',
    'Chicchan', 'Chuen', 'Cit', 'Cizin', 'Cocijo', 'Colicha', 'Cozee', 'Copijcha', 'Coqueelaa', 'Coquenexo', 'Coqui',
    'Bezelao', 'Huani', 'Xee', 'Coyopa', 'Cozaana', 'Dubdo', 'Chuah', 'Chuuah', 'Ekchuah', "Etz'nab", 'Etznab', 'Fat',
    'Frog', 'Gi', 'Gii', 'Giii', 'A', "A'", 'B', 'C', 'Ch', 'D', 'E', 'F', 'G', 'H', 'K', 'L', 'M', 'N', 'O', 'P', 'Q',
    'S', 'Y', 'Z', 'Gucumatz', 'Hacha', 'Kyum', 'Hachakyum', 'Harakan', 'Hero', 'Hobnil', 'Hosanek', 'Hozanek',
    'Huechaana', 'Huichaana', 'Hun', 'Ahaw', 'Aphu', 'Batz', 'Came', 'Choen', 'Chowen', 'Hunahpu', 'Hunaphu', 'Nal',
    'Ye', 'Yeh', 'Nik', 'Pic', 'Tok', 'Hunab', 'Hunahau', 'Hunapu', 'Hunbatz', 'Hunchoen', 'Hunchouen', 'Hunhau',
    'Huracan', 'Hurrican', 'Hurukan', 'Itzam', 'Itzamcab', 'Itzamna', 'Ix', 'Balangue', 'Chebel', 'Yax', 'Chup', 'Tub',
    'Tun', 'Ixbalanque', 'Ixchel', 'Ixpiyacoc', 'Ixtab', 'Jester', 'Kacoch', 'Kam', 'Kan', 'Kanzicnal', 'Kauil',
    'Kawil', 'Ked', 'Kedo', 'Kimil', 'Kinich', 'Ajaw', 'Pakal', 'Kakmo', 'Kisin', 'Kucumatz', 'Kuh', 'Kukulcan',
    'Kulkuylkan', 'Lahun', 'Pel', 'Mbaz', 'Mdi', 'Mitlan', 'Mitnal', 'Moan', 'Monkey', 'Mse', 'Muan', 'Mulac', 'Nahual',
    'Ndan', "Ndo'yet", 'Ndoyet', 'Ndozin', 'Nohock', 'Jaguar', 'Paddler', 'Stingray', 'Olmec', 'One', 'Oxlahuntiku',
    'Palenque', 'Triad', 'Pauahtun', 'Pavahtun', 'Pichana', 'Gobeche', 'Pichanto', 'Vuh', 'Popol', 'Buj',
    'Quiabelagayo', 'Saccimi', 'Sak', 'Sotz', 'Tepeu', 'Tohil', 'Voltan', 'Votan', 'Vucab', 'Cakix', 'Vucub', 'Camé',
    'Caquix', 'Vukub', 'Bahpu', 'World', 'Tree', 'Xaman', 'Xamen', 'Xbalanque', 'Xbaquiyalo', 'Xibalba', 'Xibalbay',
    'Xmucane', 'Xpiyacoc', 'Xquic', 'Yaluk', 'Cimih', 'Cimil', 'Kaax', 'Kax', 'Zac', 'Cimi', 'Zipacna']
