names = [
    'Ac', 'Yanto,', 'Acan,', 'Acantuns,', 'Acat,', 'Ah', 'Bolom', 'Tzacab,', 'Ah', 'Bolon', "Dz'acab,", 'Ah', 'Bolon',
    'Dzacab,', 'Ah', 'Chicum', 'Ek,', 'Ah', 'Chicumek,', 'Ah', 'Ciliz,', 'Ah', 'Cuxtal,', 'Ah', 'Hoya,', 'Ah',
    'Hulneb,', 'Ah', 'Kin,', 'Ah', 'Kinchil,', 'Ah', 'Mucen', 'Cab,', 'Ah', 'Muzen', 'Cab,', 'Ah', 'Muzencab,', 'Ah',
    'Peku,', 'Ah', 'Puch,', 'Ah', 'Tzenul,', 'Ah', 'Tzul,', 'Ah', 'Uuk', 'Yol', 'Zip,', 'Ahau', 'Kin,', 'Ahpuch,',
    'Akbul,', 'Alaghom', 'Naom,', 'Alaghom', 'Naom', 'Tzentel,', 'Alphabet', 'Gods', 'Bacab,', 'Bacabs,', 'Backlum',
    'Chaam,', 'Balam,', 'Balams,', 'Balanque,', 'Becabs,', 'Belachina,', 'Ben', 'Elaba,', 'Beydo,', 'Bolon', 'Dzacab,',
    'Bolon', 'Ti', 'Ku,', 'Bolon', 'Tiku,', 'Bolon', 'Tzacab,', 'Bolon', 'Tzakab,', 'Bolontiku,', 'Bulkabil,', 'Buluc',
    'Chabtan,', 'Buluk', 'Kab', 'Cabracan,', 'Cabrakan,', 'Cacoch,', 'Cakulha,', 'Cama', 'Zotz,', 'Camazotz,', 'Can',
    'Tzicnal,', 'Caneques,', 'Cantzicnal,', 'Cauac,', 'Chaac,', 'Chaak,', 'Chac,', 'Chac', 'Chel,', 'Chac', 'Mol,',
    'Chac', 'Mool,', 'Chac', 'Uayeb', 'Xoc,', 'Chac', 'Xib', 'Chac,', 'Chacmool,', 'Chak,', 'Chaob,', 'Chibilkin,',
    'Chiccan,', 'Chicchan,', 'Chuen,', 'Cit', 'Bolon', 'Tum,', 'Cizin,', 'Cocijo,', 'Colicha', 'Cozee,', 'Copijcha,',
    'Coqueelaa,', 'Coquenexo,', 'Coqui', 'Bezelao,', 'Coqui', 'Huani,', 'Coqui', 'Xee,', 'Coyopa,', 'Cozaana', 'Dubdo',
    'Ek', 'Chuah,', 'Ek', 'Chuuah,', 'Ek', 'Zip,', 'Ekchuah,', "Etz'nab,", 'Etznab', 'Fat', 'God,', 'Frog', 'God',
    'Gi,', 'Gii,', 'Giii,', 'God', 'A,', 'God', "A',", 'God', 'B,', 'God', 'C,', 'God', 'Ch,', 'God', 'D,', 'God', 'E,',
    'God', 'F,', 'God', 'G,', 'God', 'H,', 'God', 'K,', 'God', 'L,', 'God', 'M,', 'God', 'N,', 'God', 'O,', 'God', 'P,',
    'God', 'Q,', 'God', 'S,', 'God', 'Y,', 'God', 'Z,', 'Gucumatz', 'Hacha', 'Kyum,', 'Hachakyum,', 'Harakan,', 'Hero',
    'Twins,', 'Hobnil,', 'Hosanek,', 'Hozanek,', 'Huechaana,', 'Huichaana,', 'Hun', 'Ahau,', 'Hun', 'Ahaw,', 'Hun',
    'Aphu,', 'Hun', 'Batz,', 'Hun', 'Came,', 'Hun', 'Choen,', 'Hun', 'Chowen,', 'Hun', 'Hunahpu,', 'Hun', 'Hunaphu,',
    'Hun', 'Nal,', 'Hun', 'Nal', 'Ye,', 'Hun', 'Nal', 'Yeh,', 'Hun', 'Nik,', 'Hun', 'Pic', 'Tok,', 'Hunab', 'Ku,',
    'Hunahau,', 'Hunahpu,', 'Hunaphu,', 'Hunapu,', 'Hunbatz,', 'Hunchoen,', 'Hunchouen,', 'Hunhau,', 'Huracan,',
    'Hurrican,', 'Hurukan', 'Itzam', 'Cab,', 'Itzam', 'Na,', 'Itzamcab,', 'Itzamna,', 'Ix,', 'Ix', 'Balangue,', 'Ix',
    'Balanque,', 'Ix', 'Chebel', 'Yax,', 'Ix', 'Chel,', 'Ix', 'Chup,', 'Ix', 'Tub', 'Tun,', 'Ixbalanque,', 'Ixchel,',
    'Ixpiyacoc,', 'Ixtab', 'Jester', 'Gods', 'Kacoch,', 'Kam,', 'Kan,', 'Kanzicnal,', 'Kauil,', 'Kawil,', 'Ked,',
    'Kedo,', 'Kimil,', 'Kinich', 'Ahau,', 'Kinich', 'Ahaw,', 'Kinich', 'Ajaw', 'Pakal,', 'Kinich', 'Kakmo,', 'Kisin,',
    'Kucumatz,', 'Kuh,', 'Kukulcan,', 'Kulkuylkan', 'Lahun', 'Pel', 'Mbaz,', 'Mdi,', 'Mitlan,', 'Mitnal,', 'Moan,',
    'Monkey', 'Twins,', 'Mse,', 'Muan,', 'Mulac', 'Nahual,', 'Nal,', 'Ndan,', "Ndo'yet,", 'Ndoyet,', 'Ndozin,', 'Nik,',
    'Nohock', 'Ek', 'Old', 'Black', 'God,', 'Old', 'Jaguar', 'Paddler,', 'Old', 'Stingray', 'Paddler,', 'Olmec',
    'Gods,', 'One', 'Hunahpu,', 'Oxlahuntiku', 'Paddler', 'Gods,', 'Palenque', 'Triad,', 'Pauahtun,', 'Pavahtun,',
    'Pichana', 'Gobeche,', 'Pichanto,', 'Popo', 'Vuh,', 'Popol', 'Buj,', 'Popol', 'Vuh', 'Quiabelagayo', 'Saccimi,',
    'Sak', 'Nik,', 'Sotz', 'Tepeu,', 'Tohil', 'Uayeb', 'Voltan,', 'Votan,', 'Vucab', 'Cakix,', 'Vucab', 'Came,',
    'Vucab', 'Hunahpu,', 'Vucub', 'Camé,', 'Vucub', 'Caquix,', 'Vucub', 'Hunahpu,', 'Vukub', 'Bahpu', 'World', 'Tree',
    'Xaman', 'Ek,', 'Xamen', 'Ek,', 'Xbalanque,', 'Xbaquiyalo,', 'Xibalba,', 'Xibalbay,', 'Xmucane,', 'Xpiyacoc,',
    'Xquic', 'Yaluk,', 'Yax', 'Balam,', 'Yum', 'Cimih,', 'Yum', 'Cimil,', 'Yum', 'Kaax,', 'Yum', 'Kax,', 'Yum', 'Kimil',
    'Zac', 'Cimi,', 'Zipacna,', 'Zotz']
