names = [
    'Balder', 'Baldr', 'Baldur', 'Baudihillie', 'Bestla', 'Beyla', 'Bifrost', 'Bilfrost', 'Bjort', 'Blid', 'Bor',
    'Borr', 'Brage', 'Bragi', 'Brunhilde', 'Brunhilt', 'Brunnhilde', 'Brynhild', 'Buri', 'Byggvir', 'Bylgia', 'Aasgard',
    'Aegir', 'Aesir', 'Alfheim', 'Alfheimr', 'Andhrimnir', 'Andvari', 'Angerbda', 'Angrboda', 'Asbru', 'Asegeir',
    'Asgaard', 'Asgard', 'Ask', 'Askr', 'Astrild', 'Audhumbia', 'Audhumla', 'Audumbla', 'Audumla', 'Aurgelmir',
    'Aurvandil', 'Aurvandill', 'Eir', 'Elli', 'Embla', 'Fafnir', 'Fenric', 'Fenrir', 'Fenris', 'Fenrisulfr', 'Fjorgyn',
    'Forseti', 'Freya', 'Freyja', 'Freyr', 'Fricco', 'Frigg', 'Frigga', 'Frost Giant', 'Fulla', 'Gangleri', 'Garm',
    'Gefion', 'Gefjon', 'Geirrod', 'Geirskokul', 'Gerd', 'Gerda', 'Gerdhr', 'Gersemi', 'Gerth', 'Gertrude', 'Gerutha',
    'Ginnungagap', 'Gjalp', 'Gladsheim', 'Gladsheimr', 'Glut', 'Godheim', 'Goll', 'Gondul', 'Gotterdammerung', 'Greip',
    'Grid', 'Groa', 'Gudrun', 'Guinn', 'Gullintani', 'Gullveig', 'Gulveig', 'Gunn', 'Gunnlod', 'Guttorm', 'Hardgrep',
    'Harr', 'Hati', 'Havamal', 'Heid', 'Heidrun', 'Heimdall', 'Heimdallr', 'Hel', 'Hela', 'Helgardh', 'Helheim',
    'Helheimr', 'Hell', 'Herfjoturr', 'Hermod', 'Hermoth', 'Hertha', 'Hild', 'Hladgunnr', 'Hlin', 'Hlock', 'Hlodyn',
    'Hnoss', 'Hnossa', 'Hod', 'Hodur', 'Hohnir', 'Holda', 'Holle', 'Holler', 'Honir', 'Hraesvelg', 'Hreidmar', 'Hrist',
    'Hrungnir', 'Hrym', 'Huldra', 'Hyldemoer', 'Hymir', 'Hyndla', 'Hyrokkin', 'Idunn', 'Jafenhar', 'Jafnharr',
    'Jarnsaxa', 'Jeirolul', 'Jola', 'Jord', 'Jormungand', 'Jotnar', 'Jotunheim', 'Judur', 'Kara', 'Kvasir', 'Laga',
    'Laufey', 'Lif', 'Lifthrasir', 'Liv', 'Loder', 'Lofn', 'Loki', 'Lokkju', 'Lopter', 'Lopti', 'Magni', 'Manheimr',
    'Mani', 'Mannheim', 'Midgard', 'Mimir', 'Mist', 'Mjolnir', 'Modgud', 'Modi', 'Muspelheim', 'Muspelheimr', 'Muspell',
    'Muspellsheimr', 'Narfi', 'Nari', 'Narvi', 'Nehalennia', 'Nibelungs', 'Nicor', 'Nidavellir', 'Nidhogg', 'Nidhoggr',
    'Niflheim', 'Niflheimr', 'Niflhel', 'Nithhogg', 'Njoerd', 'Njor', 'Njord', 'Njoror', 'Njorth', 'Norns', 'Nott',
    'Od', 'Odin', 'Odinn', 'Odur', 'Oller', 'Othinn', 'Otr', 'Radgrid', 'Ragnarok', 'Ran', 'Ratatosk', 'Ratatoskr',
    'Regin', 'Rind', 'Rindr', 'Saga', 'Sibilja', 'Siegfried', 'Sif', 'Sigurd', 'Sigyn', 'Sjofn', 'Skadi', 'Skaoi',
    'Skeggiold', 'Skirnir', 'Skogul', 'Skoll', 'Skuld', 'Sleipner', 'Sleipnir', 'Snotra', 'Sol', 'Surt', 'Suttung',
    'Svartalfheim', 'Svartalfheimr', 'Syn', 'Thialfi', 'Thiassi', 'Thor', 'Thridi', 'Thrud', 'Thrudheim', 'Tyr', 'Ull',
    'Uller', 'Ullr', 'Urd', 'Urth', 'Vafthrudnir', 'Vafthruthnir', 'Vaganhope', 'Vak', 'Valder', 'Valhalla',
    'Valkyries', 'Valkyrja', 'Valtam', 'Vanaheim', 'Vanir', 'Ve', 'Verdandi', 'Vidar', 'Vili', 'Ville', 'Volsungs',
    'Vuldr', 'Yggdrasil', 'Yggdrasill', 'Ymir']
