names = [
    'Abeguwo', 'Abere', 'Adaro', 'Adi', 'Mailagu', 'Afekan', 'Agunua', 'Ahoeitu', 'Tupuai', 'Aiaru', 'Aku', 'Muki',
    'Alalahe', 'Alilmenehune', 'Aluelop', 'Aluluei', 'Ao', 'Kahiwahiwa', 'Kanapanapa', 'Nue', 'Pakarea', 'Potano',
    'Pour', 'Roa', 'Takawe', 'Hau', 'Ko', 'Hai', 'Mantangi', 'Areop', 'Enap', 'It', 'Eonin', 'Aroonoona', 'Arununa',
    'Atanua', 'Atea', 'Au', 'Aumakua', 'Babamik', 'Bue', 'Dakuwanga', 'Darvi', 'Degei', 'Demas', 'Diwa', 'Zib',
    'Dudugera', 'Eitumatupua', "Fa'ahotu", 'Ahotu', 'Fardu', 'Fati', 'Faumea', "Fe'e", 'Fe', 'Flaming', 'Teeth',
    'Godsticks', 'Goga', 'Gogo', 'Gora', 'Daileng', 'Hana', 'Haumea', 'Haumiatiketike', 'Haumietiketike', "Hi'aka",
    "Hi'iaka", 'Hiiaka', "Hikule'o", 'Hikule', 'Hina', 'Ika', 'Uri', 'Hine', 'Keha', 'Nuitepo', 'Titama', 'Hinenuitepo',
    'Hinetitama', 'Hoa', 'Tapu', 'Honoyeta', 'Hukere', 'Nui', 'Tere', 'Maeri', 'Ilaheua', 'Ilaheva', 'Ira', 'Waru',
    'Jari', 'Jugumishanta', 'Kae', 'Kahausibware', 'Kahoali', 'Aba', 'Kaitangata', 'Kakamora', "Kamapua'a", 'Kamapuaa',
    'Kamarong', 'Kanaloa', 'Kane', 'Kang', 'Kilyaki', 'Pua', 'Kua', 'Akahi', 'Kuku', 'Lau', 'Kumu', 'Honua', 'Kwolam',
    'Laka', 'Lalo', 'Latmikaik', 'Laufakanaa', 'Lejman', 'Lingadua', 'Lioumere', "Lo'au", "Lo'o", 'Lo', 'Loau', 'Lono',
    'Lugeilan', 'Mahina', 'Mahu', 'Fatu', 'Rau', 'Mahuika', 'Make', 'Makea', 'Makemake', 'Marakihau', 'Marawa', 'Maru',
    'Matabiri', 'Matagaigai', 'Maui', 'Menchune', 'Mesede', 'Milu', 'Miru', 'Moai', 'Moko', 'Mon', 'Moro', 'Funa',
    'Morofuna', 'Motikitik', 'Murimuria', 'Atibu', 'Kaa', 'Kika', 'Nanganana', 'Naniumiap', 'Nareau', 'Ndauthina',
    'Ndengi', 'Nei', 'Tituaabine', 'Ngani', 'Vatu', 'Ngarara', 'Ngaru', 'Ni', "Nu'u", 'U', 'Oa', 'Rove', 'Olifat',
    'Olofat', 'Oma', 'Rumufu', 'Oro', 'Pahuanuiapitaaitera', 'Paikea', 'Pak', "A'a", 'Palulop', 'Papa', 'Tu', 'Anuku',
    'Papatuanuku', 'Pele', 'Pelei', 'Pere', 'Po', 'Pouakai', "Pu'uhele", 'Pu', 'Uhele', 'Puarata', 'Pulotu', 'Qasavara',
    'Qat', 'Raivuki', 'Rakim', 'Rangi', 'Ranginui', 'Ratu', 'Mai', 'Bulu', 'Rehua', 'Rigi', "Ro'o", 'Ro', 'Rokola',
    'Rongo', 'Rongomatane', 'Roua', 'Ruaumoko', 'Sina', 'Sisimatailaa', 'Soido', 'Solal', 'Sosom', "Ta'arda", "Ta'aroa",
    'Ta', 'Arda', 'Aroa', 'Oroa', 'Taburimai', 'Tagaro', 'Tahiri', 'Tea', 'Tahu', 'Tama', 'Tane', 'Mahuta',
    'Tanemahuta', 'Tangaloa', 'Tangaroa', 'Tangata', 'Tangatamanu', "Tangi'ia", 'Tangi', 'Ia', 'Taonoui', 'Taonouit',
    'Tautohito', 'Tawhiri', 'Tawhirimatea', 'Ikawai', 'Nao', 'Reere', 'Teanoi', 'Tiki', 'Wananga', 'Timbehes',
    'Tinandi', 'Thambonga', 'Tintrau', "Titua'abine", 'Titua', 'Abine', 'To', 'Kabinana', 'Karvuvu', 'Toropotaa', 'Toi',
    'Totoima', 'Tpereaki', 'Matavenga', 'Tuli', 'Tumatauenga', 'Tumuitearetoka', 'Tunaroa', 'Turi', 'Turukawa',
    'Uenuku', 'Ulupoka', 'Unihi', 'Pili', 'Vari', 'Varima', 'Takere', 'Vehine', 'Hae', 'Wahini', 'Waiora', 'Whaitiri',
    'Whiro', 'Yalafath']
