names = [
    'Abeguwo,', 'Abere,', 'Adaro,', 'Adi', 'Mailagu,', 'Afekan,', 'Agunua,', 'Ahoeitu,', 'Ai', 'Tupuai,', 'Aiaru,',
    'Aku', 'Aku,', 'Ala', 'Muki,', 'Alalahe,', 'Alilmenehune,', 'Aluelop,', 'Aluluei,', 'Ao,', 'Ao', 'Kahiwahiwa,',
    'Ao', 'Kanapanapa,', 'Ao', 'Nue,', 'Ao', 'Pakarea,', 'Ao', 'Potano,', 'Ao', 'Pour,', 'Ao', 'Roa,', 'Ao', 'Takawe,',
    'Apu', 'Hau,', 'Apu', 'Ko', 'Hai,', 'Apu', 'Mantangi,', 'Areop,', 'Areop', 'Enap,', 'Areop', 'It', 'Eonin,',
    'Aroonoona,', 'Arununa,', 'Atanua,', 'Atea,', 'Au,', 'Aumakua', 'Babamik,', 'Bird', 'Man,', 'Bue', 'Dakuwanga,',
    'Darvi,', 'Degei,', 'Demas,', 'Diwa', 'Zib,', 'Dudugera', 'Eitumatupua', "Fa'ahotu,", 'Fa', 'Ahotu,', 'Fardu,',
    'Fati,', 'Faumea,', "Fe'e,", 'Fe', 'E,', 'Flaming', 'Teeth', 'Godsticks,', 'Goga,', 'Gogo,', 'Gora', 'Daileng',
    'Hana,', 'Haumea,', 'Haumiatiketike,', 'Haumietiketike,', "Hi'aka,", "Hi'iaka,", 'Hiiaka,', "Hikule'o,", 'Hikule',
    'O,', 'Hina,', 'Hina', 'Ika,', 'Hina', 'Uri,', 'Hine,', 'Hine', 'Keha,', 'Hine', 'Nuitepo,', 'Hine', 'Titama,',
    'Hinenuitepo,', 'Hinetitama,', 'Hoa', 'Tapu,', 'Honoyeta,', 'Hukere,', 'Hukere', 'Nui', 'Ika', 'Tere', 'Maeri,',
    'Ilaheua,', 'Ilaheva,', 'Io,', 'Ira', 'Waru', 'Jari,', 'Jugumishanta', 'Kae,', 'Kahausibware,', 'Kahoali,',
    'Kai', 'N', 'Tiku', 'Aba,', 'Kaitangata,', 'Kakamora,', "Kamapua'a,", 'Kamapuaa,', 'Kamarong,', 'Kanaloa,', 'Kane,',
    'Kang,', 'Kilyaki,', 'Ku,', 'Ku', 'Ka', 'Pua,', 'Ku', 'Kua', 'Akahi,', 'Kuku', 'Lau,', 'Kumu', 'Honua,', 'Kwolam',
    'Laka,', 'Lalo', 'Honua,', 'Latmikaik,', 'Laufakanaa,', 'Lejman,', 'Lingadua,', 'Lioumere,', "Lo'au,", "Lo'o,",
    'Lo', 'O,', 'Loa,', 'Loau,', 'Lono,', 'Lugeilan', 'Mahina,', 'Mahu', 'Fatu', 'Rau,', 'Mahuika,', 'Make', 'Make,',
    'Makea,', 'Makemake,', 'Marakihau,', 'Marawa,', 'Maru,', 'Matabiri,', 'Matagaigai,', 'Maui,', 'Menchune,',
    'Mesede,', 'Milu,', 'Miru,', 'Moai,', 'Moko,', 'Mon', 'Moko,', 'Moro', 'Funa,', 'Morofuna,', 'Motikitik,',
    'Murimuria', 'Na', 'Atibu,', 'Na', 'Kaa,', 'Na', 'Kika,', 'Nanganana,', 'Naniumiap,', 'Nareau,', 'Ndauthina,',
    'Ndengi,', 'Nei', 'Tituaabine,', 'Ngani', 'Vatu,', 'Ngarara,', 'Ngaru,', 'Ni,', "Nu'u,", 'Nu', 'U', 'Oa', 'Rove,',
    'Olifat,', 'Olofat,', 'Oma', 'Rumufu,', 'Oro', 'Pahuanuiapitaaitera,', 'Paikea,', 'Pak', "A'a,", 'Pak', 'A', 'A,',
    'Palulop,', 'Papa,', 'Papa', 'Tu', 'Anuku,', 'Papatuanuku,', 'Pele,', 'Pelei,', 'Pere,', 'Po,', 'Pouakai,',
    "Pu'uhele,", 'Pu', 'Uhele,', 'Puarata,', 'Pulotu', 'Qasavara,', 'Qat', 'Raivuki,', 'Rakim,', 'Rangi,', 'Ranginui,',
    'Ratu', 'Mai', 'Bulu,', 'Rehua,', 'Rigi,', "Ro'o,", 'Ro', 'O,', 'Rokola,', 'Rongo,', 'Rongo', 'Mai,',
    'Rongomatane,', 'Roua,', 'Ruaumoko', 'Sina,', 'Sisimatailaa,', 'Soido,', 'Solal,', 'Sosom', "Ta'arda,", "Ta'aroa,",
    'Ta', 'Arda,', 'Ta', 'Aroa,', 'Ta', 'Oroa,', 'Taburimai,', 'Tagaro,', 'Tahiri', 'Ma', 'Tea,', 'Tahu,', 'Tama,',
    'Tane,', 'Tane', 'Mahuta,', 'Tanemahuta,', 'Tangaloa,', 'Tangaroa,', 'Tangata', 'Manu,', 'Tangatamanu,',
    "Tangi'ia,", 'Tangi', 'Ia,', 'Taonoui,', 'Taonouit,', 'Tara,', 'Tautohito,', 'Tawhiri,', 'Tawhiri', 'Ma', 'Tea,',
    'Tawhirimatea,', 'Te', 'Ikawai,', 'Te', 'Nao,', 'Te', 'Reere,', 'Teanoi,', 'Tiki,', 'Tiki', 'Wananga,', 'Timbehes,',
    'Tinandi', 'Thambonga,', 'Tintrau,', "Titua'abine,", 'Titua', 'Abine,', 'To', 'Kabinana,', 'To', 'Karvuvu,', 'To',
    'Toropotaa,', 'Toi', 'Mata,', 'Totoima,', 'Tpereaki,', 'Tu,', 'Tu', 'Matavenga,', 'Tuli,', 'Tumatauenga,',
    'Tumuitearetoka,', 'Tunaroa,', 'Turi', 'A', 'Faumea,', 'Turukawa', 'Uenuku,', 'Ulupoka,', 'Unihi', 'Pili', 'Vari,',
    'Varima', 'Te', 'Takere,', 'Vehine', 'Hae', 'Wahini', 'Hai,', 'Waiora,', 'Whaitiri,', 'Whiro', 'Yalafath']
