# -*- coding: utf-8 -*-
from __future__ import unicode_literals
names = [
    'Abeona', 'Abundantia', 'Acca', 'Larentia', 'Adeona', 'Aequitas', 'Aestas', 'Africus', 'Agnostos', 'Theos', 'Aius',
    'Locutius', 'Locutus', 'Albunea', 'Alemonia', 'Angerona', 'Angita', 'Ani', 'Perenna', 'Annona', 'Antinous',
    'Aquilo', 'Artume', 'Aurora', 'Auster', 'Bacchus', 'Bellifluficus', 'Bellona', 'Bona', 'Dea', 'Bonus', 'Eventus',
    'Britannia', 'Bubona', 'Caca', 'Calva', 'Camenae', 'Candelifera', 'Canens', 'Cardea', 'Carmenta', 'Carna', 'Ceres',
    'Clementia', 'Cloacina', 'Concordia', 'Consuales', 'Ludi', 'Consualia', 'Consus', 'Credulitas', 'Cuba', 'Cupid',
    'Cupra', 'Decima', 'Di', 'Manes', 'Penates', 'Diana', 'Dies', 'Pater', 'Dis', 'Disciplina', 'Discordia', 'Dius',
    'Fidus', 'Djous', 'Egeria', 'Egestes', 'Empanda', 'Endovelicus', 'Evan', 'Evander', 'Fabulinus', 'Fama', 'Fame',
    'Fames', 'Fascinus', 'Fatua', 'Fauna', 'Faunus', 'Fauonius', 'Faustulus', 'Februus', 'Felicitas', 'Feronia',
    'Fides', 'Flora', 'Fons', 'Fontus', 'Fornax', 'Fortuna', 'Fraud', 'Fraus', 'Friendship', 'Genius', 'Hercules',
    'Hersilia', 'Hippona', 'Honor', 'Horta', 'Ilia', 'Ilythyia', 'Leucothea', 'Invidia', 'Iovis', 'Iupiter', 'Iuppiter',
    'Janus', 'Jove', 'Juno', 'Jupiter', 'Justicia', 'Juturna', 'Juventas', 'Laetitia', 'Lara', 'Lares', 'Larvae',
    'Latinus', 'Laverna', 'Lemures', 'Liber', 'Libera', 'Libitina', 'Loquens', 'Losna', 'Lucifer', 'Luna', 'Lunar',
    'Lupercus', 'Mania', 'Mantus', 'Marica', 'Mars', 'Mater', 'Matuta', 'Men', 'Mena', 'Mephitis', 'Mercury', 'Minerva',
    'Medica', 'Mithras', 'Mors', 'Morta', 'Mortia', 'Mulciber', 'Necessitas', 'Neptune', 'Neptunus', 'Nicostrate',
    'Nono', 'Opis', 'Ops', 'Optimus', 'Maximus', 'Orcus', 'Pales', 'Palladium', 'Parca', 'Maurtia', 'Parcae', 'Pax',
    'Phoebus', 'Picus', 'Pietus', 'Pilumnus', 'Pleasure', 'Pluto', 'Pomona', 'Portunus', 'Postvorta', 'Proserpina',
    'Prudence', 'Pudicitia', 'Quirinus', 'Rea', 'Silvia', 'Remus', 'Robiga', 'Robigus', 'Roma', 'Romulus', 'Salacia',
    'Salus', 'Saritor', 'Saturn', 'Saturnus', 'Sequana', 'Sibyl', 'Cumae', 'Silvanus', 'Somnus', 'Spes', 'Sterculius',
    'Stercutus', 'Sterquilinius', 'Sterquilinus', 'Strenua', 'Striges', 'Sturculinus', 'Summanus', 'Suovetaurilia',
    'Susurri', 'Sylvanus', 'Tages', 'Telluno', 'Tellus', 'Terminus', 'Thalna', 'Tiberinus', 'Timores', 'Tria', 'Fata',
    'Trivia', 'Veiovis', 'Veive', 'Venus', 'Verbeia', 'Veritas', 'Vertumnus', 'Vesta', 'Victory', 'Virbius', 'Virtus',
    'Volcanus', 'Voltumna', 'Volturnus', 'Volupta', 'Voluptas', 'Vulcan', 'Vulturnus']
